-- insert into  UserInfo values(1,'saba@gmail.com','saba','$2a$10$paBlwFYCcKct55bm2c30Be7sDxMLTnrwLx15vzymUqFJG2FFV4vOq','ROLE_USER,ROLE_ADMIN');
--	 insert into  UserInfo values(2,'kirsten@gmail.com','kirsten','$2a$10$IjCY.zLTQ1vJTGazoUSkuO2jyyohUeucT/72ZeOigwQQLksLvFula','ROLE_USER');
--	 insert into  UserInfo values(3,'mathews@gmail.com','mathews','$2a$10$f478i1FZZfjsoP2VhmR.1.yQw1GR6.YCF/T0Mgak01omm0byiuMZS','ROLE_ADMIN');
--	 insert into  UserInfo values(4,'mark@gmail.com','mark','$2a$10$bHUk04BzWuITCCG6r4L5MOEm5akMdCRgGYj3Rx62NEr31.3tsCdiG','ROLE_USER,ROLE_ADMIN');